### ISSUE TITLE
Can't npm install Version 0.12.0-beta.6

### ISSUE THREAD

**Issue by vanthome** [prisma/nexus#156]
I get these errors when compiling with beta 6.
```
node_modules/nexus/dist/definitions/args.d.ts:58:36 - error TS2344: Type 'string' does not satisfy the constraint '"Int" | "Float" | "String" | "Date" | "Boolean" | "QueryFilterType" | "SortOrderEnum" | "StatusEnum" | "ID"'.

58   protected config: NexusArgConfig<string>;
                                      ~~~~~~

node_modules/nexus/dist/definitions/args.d.ts:59:54 - error TS2344: Type 'string' does not satisfy the constraint '"Int" | "Float" | "String" | "Date" | "Boolean" | "QueryFilterType" | "SortOrderEnum" | "StatusEnum" | "ID"'.

59   constructor(name: TypeName, config: NexusArgConfig<string>);
                                                        ~~~~~~

node_modules/nexus/dist/definitions/args.d.ts:60:34 - error TS2344: Type 'string' does not satisfy the constraint '"Int" | "Float" | "String" | "Date" | "Boolean" | "QueryFilterType" | "SortOrderEnum" | "StatusEnum" | "ID"'.

60   readonly value: NexusArgConfig<string>;
                                    ~~~~~~

node_modules/nexus/dist/definitions/inputObjectType.d.ts:30:32 - error TS2344: Type 'TypeName' does not satisfy the constraint '"Int" | "Float" | "String" | "Date" | "Boolean" | "QueryFilterType" | "SortOrderEnum" | "StatusEnum" | "ID"'.
  Type 'string' is not assignable to type '"Int" | "Float" | "String" | "Date" | "Boolean" | "QueryFilterType" | "SortOrderEnum" | "StatusEnum" | "ID"'.
    Type 'TypeName' is not assignable to type '"ID"'.
      Type 'string' is not assignable to type '"ID"'.

30   asArg(cfg?: NexusAsArgConfig<TypeName>): NexusArgDef<TypeName>;
```

**Comment by jasonkuhrt** [comment]
I tried a build on `nexus`. There is no type error raised at that time. This is because none of the nexus runtime-generated types are present at that point. Once they are, then `String` and `TypeName` become invalid.

**Comment by jasonkuhrt** [comment]
Did some more digging;

Only going to focus on some of the type errors right now;

First, the type error comes from the `string`s in here:

```ts
export declare class NexusArgDef<TypeName extends string> {
  readonly name: TypeName
  protected config: NexusArgConfig<string>
  constructor(name: TypeName, config: NexusArgConfig<string>)
  readonly value: NexusArgConfig<string>
}
```

coming from here:

```ts
export interface NexusArgConfig<T extends GetGen<"allInputTypes", string>>
  extends NexusAsArgConfig<T> {
  /**
   * The type of the argument, either the string name of the type,
   * or the concrete Nexus type definition
   */
  type: NexusArgConfigType<T>
}
```

coming from here:

```ts
export declare type GetGen<
  K extends GenTypesShapeKeys,
  Fallback = any
> = NexusGen extends infer GenTypes
  ? GenTypes extends GenTypesShape
    ? GenTypes[K]
    : Fallback
  : Fallback;
```

About this last block of code:

- `NexusGen` is a global interface type; Nexus exports it. It is just an empty name. The macro-like Nexus typegen feature (build at runtime, apps, using Nexus) generates types that use declaration merging to extend `NexusGen`.
- `infer` tells TypeScript to defer calculation of the type until build time (working explanation, probably leaky/bad)
- `GenTypes` (`infer GenTypes`) is a type variable name, used to reference whatever the outcome of `infer` will be
- `GenTypesShape` is the following names are record keys mapped to `any`:

```ts
export declare type GenTypesShapeKeys =
  | "context"
  | "inputTypes"
  | "rootTypes"
  | "argTypes"
  | "fieldTypes"
  | "allTypes"
  | "inheritedFields"
  | "objectNames"
  | "inputNames"
  | "enumNames"
  | "interfaceNames"
  | "scalarNames"
  | "unionNames"
  | "allInputTypes"
  | "allOutputTypes"
  | "allNamedTypes"
  | "abstractTypes"
  | "abstractResolveReturn";
```

- finally if `GenTypes` is a subtype of the above said record (b/c values are `any` a simple key subset is sufficient to be a subtype) then we get to `GenTypes[K]` which if we look way back up we see `k` is `allInputTypes`

- in order to understand what that lookup produces consider what the `infer` resolves to, once nexus typegen has run for an app, e.g.:

```
export interface NexusGenTypes {
  context: context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}
```

- the value picked is `allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames']`
- `string` is not present there

AFICT `fallback` case will never be hit in the context of a Nexus typegen built app; that is, can either of the following be `false` in a case of a nexus typegen built  app?

- ? GenTypes extends GenTypesShape
- ? GenTypes[K]

I'm going with the present presumption that they cannot. I am also going under the presumption right now that the type returned by `GenTypes[K]` will never include a `string`.

If I am correct, then it seems the solution is to stop using `string`. But I have taken some guesses and may well be wrong, in which case the fix may be in a different part of the system.

Investigating further.

**Comment by jasonkuhrt** [comment]
One place to learn more about `infer` is here https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html

**Comment by jasonkuhrt** [comment]
On my demo app, I modified the `string` and `TypeName` to be `"String"` types. At this point TypeScript is able to compile the app. As far as I can tell nothing broke. But doing this caused Nexus to fail type checking during build. So, I ended up with this approach that satisfies both sides:

```diff
diff --git a/src/definitions/args.ts b/src/definitions/args.ts
index 8205631..211c16f 100644
--- a/src/definitions/args.ts
+++ b/src/definitions/args.ts
@@ -65,7 +65,7 @@ export interface NexusArgConfig<T extends GetGen<"allInputTypes", string>>
 export class NexusArgDef<TypeName extends string> {
   constructor(
     readonly name: TypeName,
-    protected config: NexusArgConfig<string>
+    protected config: NexusArgConfig<GetGen<"allInputTypes", string>>
   ) {}
   get value() {
     return this.config;
diff --git a/src/definitions/inputObjectType.ts b/src/definitions/inputObjectType.ts
index a17dc3c..efcfa48 100644
--- a/src/definitions/inputObjectType.ts
+++ b/src/definitions/inputObjectType.ts
@@ -1,3 +1,4 @@
+import { GetGen } from "../typegenTypeHelpers";
 import { NexusTypes, NonNullConfig, withNexusSymbol } from "./_types";
 import { InputDefinitionBlock } from "./definitionBlocks";
 import { assertValidName } from "graphql";
@@ -35,7 +36,9 @@ export class NexusInputObjectTypeDef<TypeName extends string> {
   get value() {
     return this.config;
   }
-  asArg(cfg?: NexusAsArgConfig<TypeName>): NexusArgDef<TypeName> {
+  asArg(
+    cfg?: NexusAsArgConfig<GetGen<"allInputTypes", string>>
+  ): NexusArgDef<TypeName> {
     return arg({ ...cfg, type: this });
   }
 }
```

I simply continue to use the `GetGen<"allInputTypes", string>` type which produces `string` at nexus build time and some gql input type at nexus typegen time.

My understanding is still shaky, will do two things:

1. start a PR for further discussion with @tgriesser 
2. analyze the code further to better understand how the type modelling/DSL is working around GQL input types. For example I found this comment and would like to understand it better:

```ts
export interface NexusAsArgConfig<T extends GetGen<"allInputTypes", string>>
  extends CommonArgConfig {
  /**
   * Configure the default for the object
   */
  default?: GetGen2<"allTypes", T>; // TODO: Make this type-safe somehow
}
```
