### ISSUE TITLE
2 sources of truth

### ISSUE THREAD

**Issue by gotexis** [prisma/nexus#165]
Hey total noob to programming / JS / TS / Node / Graphql / English (not my first language) here. So I may have some major misunderstanding.

After reading a lot of docs, am I right to assume that with the `Nexus` + `Prisma` + `Nexus-Prisma` stack, 

I would have to define 1 SDL `datamodel.prisma` and 1 Nexus schema?

So how can one achieve `code-first` and `SDL-first` both? That's like nothing is first at all :(

How is that DRY?

How to keep them in sync?

Please, help me senpais

**Comment by pantharshit00** [comment]
Hi,

Your database schema will not essentially refect your API. That's why they are two separate entities.

In a typical ORM, you will define the database schema in terms of an object which is mapped to a table in your database schema. With Prisma, this is more declarative and you are doing it via a datamodel.


Now the confusion is caused in terms that in Prisma version 1 we are using the same GraphQL SDL to define the database schema(which is going to change in Prisma version 2). So essentially you don't have two sources of truth for the API as the datamodel schema is NOT your API. Just don't associate that with your API. We do allow you to import some types from it to save some typing but essentially it is a totally separate entity.

We also wrote a blog post on this to clear this confusion: https://www.prisma.io/blog/prisma-and-graphql-mfl5y2r7t49c/

**Comment by gotexis** [comment]
:)
